### ISSUE TITLE
Pi-hole dashboard shows zero except for domains blocked

### ISSUE THREAD

**Issue by jacobsalmela** [jacobsalmela/pi-hole#191]
I haven't been able to replicate this, but I have had about five people say their dashboard shows zeroes, even though `tail -f /var/log/pihole.log` shows that queries are working and getting blocked.  Please let me know if this is happening to you.

**Comment by OkashiOdayakana** [comment]
Wouldn't this be simply fixed by giving `www-data` read permission to the log file?

**Comment by PromoFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/1998970/12389282/9ffa61da-bdcf-11e5-84ed-95ffb07e6a3e.png)

Interestingly, I've had this issue with the dashboard since running the uninstall script. Not sure if the uninstall script is meant for general consumption, I've not actually looked into it yet, but may be part of the same issue. If not, I'll open a new one!

**Comment by PromoFaux** [comment]
As an aside, the API appears to return the correct numbers:

![image](https://cloud.githubusercontent.com/assets/1998970/12389333/e155e33e-bdcf-11e5-9eb5-3c75babd8d41.png)

**Comment by dschaper** [comment]
Hmm... I get the same behavior, uninstall then reinstall and admin page looks the same as yours...

**Comment by PromoFaux** [comment]
Found it! You can blame me for it, too..

https://github.com/jacobsalmela/AdminLTE/blob/master/index.php#L2

The file it's looking for does not exist, since I changed the files when I made the whitelisting changes (there was no need for <code>pihole.2.light.txt</code> since whitelisting is now directly done on <code>gravity.list</code>

Interestingly, <code>api.php</code> on the website get's it's number from the gravity list
https://github.com/jacobsalmela/AdminLTE/blob/master/api.php#L2

simplist fix is to change <code>index.php</code> to print the line count of <code>gravity.list</code> I'll create an issue over there

**Comment by dschaper** [comment]
Would it be hard to implement the API as a json file, and then have that available for calls, so the Admin page would populate from the json files? (Thinking about other things that are possible with a JSON API...)

**Comment by PromoFaux** [comment]
Submitted a pull for AdminLTE that should fix it. Not tested as I'm not set up at work to try it out.

The ultimate goal should be that <code>index.php</code> makes a call to <code>api.php</code>, so that there is only one block of code to edit if anything changes. I've dealt with JSON packets in jquery before, though I have 0 experience in PHP!

**Comment by dschaper** [comment]
I was just thinking that with JSON it would be extensible. We could redo the chronometer to pull from the JSON file for display and allow for more types of displays...

**Comment by PromoFaux** [comment]
Might as well keep it in <code>api.php</code>,  from a brief google, it shouldn't be too hard to consume the api from a bash script. That way, the JSON response is generated on demand, rather than on a schedule.

My next "when I'm bored" project is to get it working on my [keyboard](http://ecx.images-amazon.com/images/I/81yT-jBZ1NL._SL1500_.jpg) display!

**Comment by dschaper** [comment]
You're thinking what I was thinking, except I was thinking more of a 16x2 LCD...

**Comment by PromoFaux** [comment]
fixed:
![image](https://cloud.githubusercontent.com/assets/1998970/12391253/4b43a8d6-bdde-11e5-9dac-36c079eb685e.png)

**Comment by PromoFaux** [comment]
>Would it be hard to implement the API as a json file, and then have that available for calls, so the Admin page would populate from the json files? (Thinking about other things that are possible with a JSON API...)

@dschaper I'm working on a script tonight that outputs exactly the same as <code>api.php</code> but with the added advantage that it can be a)more extensible without having to update many web pages, b) Be a bit more intelligent when it comes to working out the total number of domains blocked as @Mcat12 [mentions here](https://github.com/jacobsalmela/AdminLTE/pull/12#issuecomment-172563379)

**Comment by dschaper** [comment]
I look forward to your changes and the PR's. How are you doing with learning Git? If you can, I highly suggest getting a trial account with Lynda.Com and doing the Git Essentials Training, it's a very good course that covers both Git and GitHub. It starts a little dry but covers a ton of essentials!

**Comment by PromoFaux** [comment]
I'm learning by trial and error, I find it much more effective than watching a video! Like, if I have a history of the mistakes I've made I can see where I've gone wrong and not make them again. I'm sure it gives others a bit of a giggle, too. :)

You guys have been well humored about my messy commits, I'm sure others may not be! But they are getting better!

**Comment by dschaper** [comment]
They are indeed getting better. The thing I like about Lynda is that it's not just watching videos. You actually set up a Git Repo and run all the commands and test on your workstation. So it's like a tutor giving you tips, but you do the work. (I guess you could just watch the videos but you wouldn't get much out of the course.) GitHub has a training course too. And then there is http://gitimmersion.com/

**Comment by PromoFaux** [comment]
see #193 .

Some cleverness will need to be done with the website to consume this.

**Comment by dschaper** [comment]
Are you up to the cleverness challenge? (I'm just a beginner with html and front end design work...)

**Comment by PromoFaux** [comment]
[one step ahead of you there](https://github.com/jacobsalmela/AdminLTE/pull/15)

**Comment by jacobsalmela** [comment]
Fixed by [AdminLTE #15](https://github.com/jacobsalmela/AdminLTE/pull/15)

**Comment by DonLexos** [comment]
Just did a full new installation and even ran the updateDashboard.sh but the bug still seems to occur on a fresh installation. Is the fix pushed to live yet?

**Comment by PromoFaux** [comment]
Could you please run `chronometer.sh -j` and tell me the output? Thanks

**Comment by DonLexos** [comment]
Sure! Step 1:

pi@pi-hole:/usr/local/bin $ chronometer.sh -j
Runtime error (func=(main), adr=11): Divide by zero
{"domains_being_blocked":"68396","dns_queries_today":"0","ads_blocked_today":"6","ads_percentage_today":""}

Checking for the 2 files, will update in a sec

**Comment by DonLexos** [comment]
Both files matched. To be 100% sure I swapped the linked copy with the one in the /admin/ folder to be sure, that did not help.

**Comment by DonLexos** [comment]
I do see that /var/log/pihole.log (which is populated) is owned by dnsmasq, not sure if that has always been the case in previous installations.

**Comment by PromoFaux** [comment]
> Runtime error (func=(main), adr=11): Divide by zero

OK, A slight oversight on my part there in percentage calculation, as I'm not checking for dns_queries_today being 0. (calculation is `ads_blocked_today / dns_queries_today * 100`)

That explains why your percentage is blank, but that doesn't effect anything else.

What it doesn't explain though is why `dns_queries_today` figure is 0, yet `ads_blocked_today` is 6

I've just run a fresh install myself and it's working fine..

>I do see that /var/log/pihole.log (which is populated) is owned by dnsmasq
I'll check mine. Is there anything in your `pihole.log`?

**Comment by DonLexos** [comment]
Yes there is, if I tail it I see it being filled when I visit websites. Since the fresh installation it grew to 439 kB already.

**Comment by PromoFaux** [comment]
Can you run the following and give me the output please?

`chronometer.sh -j` again 

and `cat /var/log/pihole.log | grep "Jan 20" | awk '/query/ {print $6}' | wc -l`

**Comment by DonLexos** [comment]
Sure!

pi@pi-hole:/ $ chronometer.sh -j
Runtime error (func=(main), adr=11): Divide by zero
{"domains_being_blocked":"68396","dns_queries_today":"0","ads_blocked_today":"6","ads_percentage_today":""}

and
pi@pi-hole:/ $ cat /var/log/pihole.log | grep "Jan 20" | awk '/query/ {print $6}' | wc -l
0

Which is odd, but here's a few lines of pihole.log now:
Jan 20 18:01:45 dnsmasq[421]: reply so0.akam.nflximg.com is <CNAME>
Jan 20 18:01:46 dnsmasq[421]: reply so.akam.nflximg.com.edgesuite.net is <CNAME>
Jan 20 18:01:46 dnsmasq[421]: reply a1123.dscg.akamai.net is 88.221.254.202
Jan 20 18:01:46 dnsmasq[421]: reply a1123.dscg.akamai.net is 88.221.254.208
Jan 20 18:01:50 dnsmasq[421]: query[A] so1.akam.nflximg.com from 192.168.1.105
Jan 20 18:01:50 dnsmasq[421]: forwarded so1.akam.nflximg.com to 8.8.4.4
Jan 20 18:01:50 dnsmasq[421]: reply so1.akam.nflximg.com is <CNAME>
Jan 20 18:01:50 dnsmasq[421]: reply so.akam.nflximg.com.edgesuite.net is <CNAME>
Jan 20 18:01:50 dnsmasq[421]: reply a1123.dscg.akamai.net is 88.221.254.208
Jan 20 18:01:50 dnsmasq[421]: reply a1123.dscg.akamai.net is 88.221.254.202

**Comment by dschaper** [comment]
And for me, can you visit `osxdaily.com` and then `cat /var/log/pihole.log | grep gravity`?

**Comment by DonLexos** [comment]
I visited the site and ran the command, not sure what you are looking for, here's the output

pi@pi-hole:/ $ cat /var/log/pihole.log | grep gravity
Binary file (standard input) matches

**Comment by dschaper** [comment]
Did you get a bunch of ads when you visited that site? I was checking to see if the blocking was working...

**Comment by PromoFaux** [comment]
Just for comparison, I too just did that considering I'm running a fresh install.

output : `Jan 20 16:48:14 dnsmasq[12668]: read /etc/pihole/gravity.list - 136204 addresses`

no ads
![image](https://cloud.githubusercontent.com/assets/1998970/12456541/376b69d2-bf98-11e5-9e0f-1c00e57257b5.png)

**Comment by DonLexos** [comment]
No no ads at all, that part is fully working. If I dig an ad domain I get the pihole IP as the server:

pi@pi-hole:/ $ dig click.buzzcity.net

; <<>> DiG 9.9.5-9+deb8u5-Raspbian <<>> click.buzzcity.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20260
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;click.buzzcity.net.            IN      A

;; ANSWER SECTION:
click.buzzcity.net.     300     IN      A       192.168.1.11

;; Query time: 2 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jan 20 18:07:31 CET 2016
;; MSG SIZE  rcvd: 63

**Comment by PromoFaux** [comment]
Same output on my side

```
; <<>> DiG 9.9.5-9+deb8u5-Raspbian <<>> click.buzzcity.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59989
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;click.buzzcity.net.            IN      A

;; ANSWER SECTION:
click.buzzcity.net.     300     IN      A       192.168.1.4

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Jan 20 17:08:44 UTC 2016
;; MSG SIZE  rcvd: 63

```

**Comment by DonLexos** [comment]
Except the install.log all files in /etc/pihole are owned by root, same as the files in /var/www/html/admin so I would think it is not a permission issue, but I could be wrong.

**Comment by PromoFaux** [comment]
I'm not sure they should be owned by root... @dschaper did something else change in the install script?

**Comment by PromoFaux** [comment]
This is most definitely a permissions issue. If I run `whitelist.sh` after a fresh install, I have to elevate it to root otherwise it fails. That was not happening on my previous install..

**Comment by dschaper** [comment]
Nothing else has changed in master with the install script. My gravity.list is owned by pi:pi. I'll try a fresh install.

**Comment by dschaper** [comment]
Here's the log for master:

```b512496 Merge pull request #207 from jacobsalmela/bugfix/Chronometer
af982a0 Move call to CheckIPv6 function into CalcBlockedDomains, rather than relying on remembering to call it before you call CalcBlockedDomains.
0327789 Merge pull request #199 from PromoFaux/master
6756843 Merge pull request #2 from PromoFaux/PromoFaux-patch-1
ac35417 Update README.md
```

**Comment by DonLexos** [comment]
/var/log/pihole.log is owned by dnsmasq on my pi, same as yours? That is the one with all the data in it and somehow the admin page cannot read that (it seems) ?

**Comment by dschaper** [comment]
Fresh install:

```
pi@raspberrypi:~/src$ ls -lac /etc/pihole/
total 22616
drwxrwxrwx   2 root root    4096 Jan 20 17:29 .
drwxr-xr-x 113 root root    4096 Jan 20 17:29 ..
-rw-r--r--   1 root root       0 Jan 20 17:29 blacklist.txt
-rw-r--r--   1 root root 6980998 Jan 20 17:29 gravity.list
-rw-r--r--   1 pi   pi      3530 Jan 20 17:29 install.log
-rw-------   1 root root   13643 Jan 20 17:29 list.0.adaway.org.domains
-rw-------   1 root root   23846 Jan 20 17:29 list.1.adblock.gjtech.net.domains
-rw-------   1 root root 1795072 Jan 20 17:29 list.2.hosts-file.net.domains
-rw-------   1 root root   49220 Jan 20 17:29 list.3.www.malwaredomainlist.com.domains
-rw-------   1 root root   41186 Jan 20 17:29 list.4.pgl.yoyo.org.domains
-rw-------   1 root root  373058 Jan 20 17:29 list.5.someonewhocares.org.domains
-rw-------   1 root root  508717 Jan 20 17:29 list.6.winhelp2002.mvps.org.domains
-rw-r--r--   1 root root 2741022 Jan 20 17:29 pihole.0.matterandlight.txt
-rw-r--r--   1 root root 1886270 Jan 20 17:29 pihole.1.supernova.txt
-rw-r--r--   1 root root 1712203 Jan 20 17:29 pihole.2.eventHorizon.txt
-rw-r--r--   1 root root 6980998 Jan 20 17:29 pihole.3.accretionDisc.txt
-rw-rw-rw-   1 root root       0 Jan 20 17:29 .useIPv6
-rw-r--r--   1 root root     125 Jan 20 17:29 whitelist.txt
```

**Comment by dschaper** [comment]
Yep
```
-rw-r--r--  1 dnsmasq  root      14122 Jan 20 17:29 pihole.log
```

**Comment by PromoFaux** [comment]
@dschaper  what do you get from `chronometer.sh -j` and what does your dashboard look like?

**Comment by DonLexos** [comment]
Mine
```
pi@pi-hole:/ $ ls -lac /etc/pihole/
total 14084
drwxrwxrwx  2 root root    4096 Jan 20 17:25 .
drwxr-xr-x 85 root root    4096 Jan 20 17:54 ..
-rw-rw-rw-  1 root root       0 Jan 20 17:24 blacklist.txt
-rw-rw-rw-  1 root root 2601359 Jan 20 17:25 gravity.list
-rw-rw-rw-  1 pi   pi     18863 Jan 20 17:24 install.log
-rw-rw-rw-  1 root root   13643 Jan 20 17:24 list.0.adaway.org.domains
-rw-rw-rw-  1 root root   23846 Jan 20 17:24 list.1.adblock.gjtech.net.domains
-rw-rw-rw-  1 root root 1795112 Jan 20 17:24 list.2.hosts-file.net.domains
-rw-rw-rw-  1 root root   49220 Jan 20 17:24 list.3.www.malwaredomainlist.com.domains
-rw-rw-rw-  1 root root   41186 Jan 20 17:24 list.4.pgl.yoyo.org.domains
-rw-rw-rw-  1 root root  373058 Jan 20 17:24 list.5.someonewhocares.org.domains
-rw-rw-rw-  1 root root  508717 Jan 20 17:24 list.6.winhelp2002.mvps.org.domains
-rw-rw-rw-  1 root root 2741061 Jan 20 17:24 pihole.0.matterandlight.txt
-rw-rw-rw-  1 root root 1886299 Jan 20 17:24 pihole.1.supernova.txt
-rw-rw-rw-  1 root root 1712232 Jan 20 17:24 pihole.2.eventHorizon.txt
-rw-rw-rw-  1 root root 2601393 Jan 20 17:24 pihole.3.accretionDisc.txt
-rw-rw-rw-  1 root root     146 Jan 20 17:24 whitelist.txt
```

**Comment by dschaper** [comment]
```
pi@raspberrypi:~/src$ chronometer.sh -j
{"domains_being_blocked":"68396","dns_queries_today":"57","ads_blocked_today":"0","ads_percentage_today":"0"}
```
![capture](https://cloud.githubusercontent.com/assets/2782850/12457349/d6fb3a3a-bf58-11e5-8679-73c4556454f4.PNG)

**Comment by PromoFaux** [comment]
are you sure your web files were updated? That Domains being blocked bug was fixed.....

**Comment by dschaper** [comment]
I'll wipe all and start fresh.

**Comment by PromoFaux** [comment]
I've just been doing the uninstall script and then clearing out `/var/www/html`

**Comment by dschaper** [comment]
I haven't tried the script, I just `sudo rm -r /etc/pihole /var/www/html/pihole/ /var/log/pihole.log`

**Comment by DonLexos** [comment]
pi@pi-hole:/usr/local/bin $ updateDashboard.sh
Already up-to-date.

**Comment by dschaper** [comment]
![capture](https://cloud.githubusercontent.com/assets/2782850/12457497/ac7fcc5c-bf59-11e5-94ac-de3661fa634b.PNG)

**Comment by PromoFaux** [comment]
don't forget `/var/www/html/admin`

**Comment by dschaper** [comment]
Ah, thanks, missing that one.

**Comment by PromoFaux** [comment]
also, does your `/var/www/html/admin/api.php` or '/var/www/html/admin/index.php` match the master?

**Comment by dschaper** [comment]
Getting a cup of coffee... Engaging brain...

**Comment by PromoFaux** [comment]
This is what I get after running the uninstall script and clearing down '/var/www/html/' 

![image](https://cloud.githubusercontent.com/assets/1998970/12457560/0a22d03c-bf9d-11e5-9953-c978b821df4e.png)

**Comment by PromoFaux** [comment]
>Getting a cup of coffee... Engaging brain...

I've stayed an hour and a half later at work than I should have... whoops! I'll give it some thought on the drive home

**Comment by dschaper** [comment]
Okay, my admin is working now...

**Comment by PromoFaux** [comment]
Excellent...! as for the root ownership stuff, that wasn't an issue before, so something has changed somewhere.. perhaps @jacobsalmela can point us in the right direction.

More to the point though, what is @DonLexos doing differently from us? If our Admin pages are working and the chrono -j output isn't falling over.....

This is new:

```
pi@raspberrypi:/etc/pihole $ whitelist.sh google-analytics.com
** Adding google-analytics.com to whitelist file
/usr/local/bin/whitelist.sh: line 85: /etc/pihole/whitelist.txt: Permission denied
** Modifying Hosts File
** Whitelisting a total of 7 domains...
** Refresh lists in dnsmasq...
```

I didn't have to sudo it before.

**Comment by PromoFaux** [comment]
Interestingly running `whitelist.sh` as root changes the ownership of `gravity.list` to `pi`

**Comment by dschaper** [comment]
Do you want to open a new issue for that one?

**Comment by PromoFaux** [comment]
I'll do that when I get home once I've given it some thought. The question is.. SHOULD those files all be owned by root after install?

**Comment by dschaper** [comment]
I don't think so, they should be owned by Pi for now. In the future they will all be owned by the pihole user, or which ever user Pi-Hole operates under.

**Comment by PromoFaux** [comment]
The answer may lay in these commits by @jacobsalmela 
![image](https://cloud.githubusercontent.com/assets/1998970/12457785/7ff1bb7e-bf9e-11e5-93e2-a881cf195e70.png)

This is the first time I've done a fresh install since then. 

_OK OK I'm going home now!!_

**Comment by DonLexos** [comment]
Ok well tried the following:
remove the /var/www/html/admin 
run /usr/bin/local/updateDashboard.sh

All files in /var/www/html/admin are owned by root again, Admin console still does not work. Could it be it tries to write somewhere that is not allowed?

**Comment by DonLexos** [comment]
Did an installation over the current one, notices a few curl errors along the process:
curl: (6) Could not resolve host: raw.githubusercontent.com

Not sure if it auto-retries, but  raw.githubusercontent.com resolves fine (from the pi) when I dig the domain. Odd.

**Comment by dschaper** [comment]
I don't think `curl` is set to auto-retry. Can you give the Pi a reboot?

**Comment by DonLexos** [comment]
Well checked the install script, only files that are downloaded from batch are the install scripts, seems to go wrong here
```
installScripts(){
$SUDO curl -o /usr/local/bin/gravity.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/gravity.sh
$SUDO curl -o /usr/local/bin/chronometer.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/chronometer.sh
$SUDO curl -o /usr/local/bin/whitelist.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/whitelist.sh
$SUDO curl -o /usr/local/bin/blacklist.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/blacklist.sh
$SUDO curl -o /usr/local/bin/piholeLogFlush.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/piholeLogFlush.sh
$SUDO curl -o /usr/local/bin/updateDashboard.sh https://raw.githubusercontent.com/jacobsalmela/pi-hole/master/advanced/Scripts/updateDashboard.sh
$SUDO chmod 755 /usr/local/bin/{gravity,chronometer,whitelist,blacklist,piholeLogFlush,updateDashboard}.sh
}
```
But only the first two. . .and even when I redo the curl and get the files that does not resolve it . . 

Did the reboot, did not change anything in my pi admin interface

**Comment by DonLexos** [comment]
I can also attempt a clean installation if that helps, this is a Raspbian Jessy Lite system, not sure if the outcome would be the same. I installed Jessy, fundled with the keyboard settings, did an apt-get update/upgrade and then ran the installer. Whitelisted google analytics, not much else.

**Comment by dschaper** [comment]
Doing a `sudo curl` is going to pull those as root, we may need to update that part of the script and do a `sudo chown` along with the `sudo chmod`...

**Comment by dschaper** [comment]
If you want to try a clean install, go ahead. It shouldn't matter if you're using the lite or the full version, just a personal preference really. I use the lite because I run headless on a Class 4 card and it's quicker to reflash the smaller image.

**Comment by DonLexos** [comment]
Well, new installation Jese Lite, no apt-get anything (since the pi script does that when you install it), so vanilla installation, ran the script, reboot, it works, including the pi-hole admin console... intended behavior, but really no clue what I did different than before, other than I reinstalled on a different SD card which I doubt could be it.

**Comment by dschaper** [comment]
Yeah, I don't know how a change in uSD cards could be a difference. I'll go ahead and close this one out, but if you run into issues again we can re-open in the future. Thanks for the assistance though!

**Comment by dschaper** [comment]
Don't forget to resize your root partition though.

**Comment by DonLexos** [comment]
Oh I have, have to run raspi-config anyway to get out of the EN keyboard (and timezone) and set it to US intl. As far as I can tell it works :-) Thanks for your help guys!

**Comment by mattlward** [comment]
I am having this problem as well... It started after my last upgrade/update and pihole reinstall for an upgrade.  It will run fine for a few hours and then just stops reporting stats.  I have also done an uninstall and reinstall.
